[package]
name = "rust_local_publisher"
version = "0.1.0"
edition = "2021"
authors = ["Adam Tarcali <adm.tarcali@gmail.com"]

[dependencies]
clap = "4.5.20"
serde = "1.0.214"
serde_json = "1.0.132"
reqwest = "0.12.9"
